<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <AssemblyName>SLine</AssemblyName>
    <RootNamespace>SLine</RootNamespace>
    <Version>1.0.0</Version>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" PrivateAssets="all" ExcludeAssets="runtime"/>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all"/>
    <PackageReference Include="BepInEx.Core" Version="5.*"/>
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="mscorlib">
      <HintPath>..\..\COMPILER_HERE\game\mscorlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System">
      <HintPath>..\..\COMPILER_HERE\game\System.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>..\..\COMPILER_HERE\game\System.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>..\..\COMPILER_HERE\game\netstandard.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\COMPILER_HERE\game\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
      <Publicize>True</Publicize>
    </Reference>
    <Reference Include="Mirage">
      <HintPath>..\..\COMPILER_HERE\game\Mirage.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\COMPILER_HERE\game\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\COMPILER_HERE\game\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\COMPILER_HERE\game\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\COMPILER_HERE\game\UnityEngine.UIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\COMPILER_HERE\game\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Rewired_Core">
      <HintPath>..\..\COMPILER_HERE\game\Rewired_Core.dll</HintPath>
      <Private>False</Private>
      <Publicize>True</Publicize>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\ExtraInput\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="ExtraInputActions.json" />
  </ItemGroup>

</Project>
